name: 📦 Packing
description: Push image to TCR
author: guotingchaopr@gmail.com

on:
  release:
    types: [created, edited, published]
  workflow_dispatch:
env:
  TCR_URL: ccr.ccs.tencentyun.com

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build TCR image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: my-app
          tags: latest ${{ github.sha }} ${{ github.event.release.tag_name }}

      - name: Push To Tencent Cloud Registry
        id: push-to-tcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: $TCR_URL
          username: ${{secrets.TENCENT_REGISTRY_USERNAME}}
          password: ${{secrets.TENCENT_REGISTRY_PASSWORD}}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-tcr.outputs.registry-paths }}"
